### PR TITLE
Add CODE_OF_CONDUCT.md

### LINKED ISSUE #9: Add CODE_OF_CONDUCT.md
Add the Code of Conduct as a markdown file named CODE_OF_CONDUCT.md in /.github directory for GitHub to link to (refer to the bottom right of Issues when creating them).

This Code of Conduct uses the [Citizen Code of Conduct](https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md) template.

This issue and subsequent Pull Request are intended for the team to review and approve the contribution guidelines before @christopher-alba merges them.

### PR DESCRIPTION
**Pull request by R055A**
Solves Issue #9 

Add the Code of Conduct as a markdown file named CODE_OF_CONDUCT.md in /.github directory for GitHub to link to (refer to the bottom right of Issues when creating them).

This Code of Conduct uses the [Citizen Code of Conduct](https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md) template.

This issue and subsequent Pull Request are intended for the team to review and approve the contribution guidelines before @christopher-alba merges them.

### CODE REVIEW

**Review by hpar461 — APPROVED** [review]

**Review by christopher-alba — APPROVED** [review]
This is really thorough haha nice!

**Review by kimslor — APPROVED** [review]

**Review by Xiaoqi510 — COMMENTED** [review]
It looks quite nice! Thank you for your docs!!!

**Review by Xiaoqi510 — APPROVED** [review]

**Review by yuchendong13 — APPROVED** [review]

**Review by hiin3d55 — APPROVED** [review]
LGTM!

**Review by emettreio — APPROVED** [review]
Very sensible code of conduct. Should be a pleasure to contribute here (even if we have to leave the fireworks at home 😢 )

**Review by AlexMiao7 — APPROVED** [review]

**Review by Tvo465 — APPROVED** [review]
Very clear and seems to cover everything, seems great :)

**Review by qzho236 — APPROVED** [review]

**Pull request merged**
