### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #2: Add CONTRIBUTING.md
Add the contribution guideline as a markdown file named CONTRIBUTING.md in /.github directory for GitHub to link to (refer to the bottom right of Issues when creating them).

This issue and subsequent Pull Request are intended for the team to review and approve the contribution guidelines before @christopher-alba merges them, and also as an example on how to make and use an Issue and Pull Request using a GitHub Kanban project board.

### PR DESCRIPTION
**Pull request by R055A**
Issue: #2 

Add the contribution guideline as a markdown file named CONTRIBUTING.md in /.github directory for GitHub to link to (refer to the bottom right of Issues when creating them).

This issue and subsequent Pull Request are intended for all the team to review and approve the contribution guidelines before @christopher-alba merges them; like signing a contract.

### CODE REVIEW

**Review by yuchendong13 — DISMISSED** [review]
Looks good, thanks

**Review by christopher-alba — DISMISSED** [review]
LGTM!

**Review by AlexMiao7 — DISMISSED** [review]
nice

**Review by hpar461 — DISMISSED** [review]
Looks great!

**Review by christopher-alba — DISMISSED** [review]

**Review by yuchendong13 — DISMISSED** [review]

**Review by AlexMiao7 — DISMISSED** [review]

**Review by kimslor — APPROVED** [review]

**Review by hpar461 — DISMISSED** [review]

**Review by Tvo465 — DISMISSED** [review]
Looks good.

**Review by kimslor — DISMISSED** [review]

**Review by Xiaoqi510 — DISMISSED** [review]

**Review by hiin3d55 — DISMISSED** [review]

**Review by kimslor — APPROVED** [review]

**Review by yuchendong13 — APPROVED** [review]

**Review by christopher-alba — APPROVED** [review]

**Review by AlexMiao7 — APPROVED** [review]

**Review by emettreio — APPROVED** [review]
Great stuff. Very clear and explicit!

**Review by Xiaoqi510 — APPROVED** [review]

**Review by hpar461 — APPROVED** [review]

**Review by hiin3d55 — APPROVED** [review]
LGTM!

**Review by Tvo465 — APPROVED** [review]
looks good

**Comment by christopher-alba** [comment]
**NOTE:** The Netlify checks are failing because currently the PR branch does not have any package.json and netlify scripts, as opposed to the main. We as a group have chosen to bypass these Netlify checks because of this when merging the PR. This is because the changes made only involve adding a markdown file, and nothing else.

**Review by qzho236 — APPROVED** [review]

**Pull request merged**
