### PR TITLE
Added CommunityPreviewComponent and Communities page

### LINKED ISSUE #33: Communities Page Basic Layout
- contains a list of all the communities (create a communityPreview component)
- contains a searchbar to search all the communities
- contains a new community button
image

### PR DESCRIPTION
**Pull request by yuchendong13**
# Description

- contains a list of all the communities (create a communityPreview component)
- contains a searchbar to search all the communities
- contains a new community button

## Related Issue

Solves [Issue #33](https://github.com/SE701-T5/Frontend/issues/33)

## Type of change

- [x] New feature (enhancement)

## How Has This Been Tested?

- [x] Manual testing

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [x] Is the code documented, particularly in hard-to-understand areas?
- [x] Does the code build without new warnings?
- [x] Has testing been performed that proves changes are effective and work?
- [x] Has a self- and/or peer-review of the code been performed?
- [x] Have dependent changes been merged and published in downstream modules?
- [ ] Does all new and existing automated testing pass?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

### CODE REVIEW

**Review by christopher-alba — DISMISSED** [review]
This is looking great!

**Review by Tvo465 — CHANGES_REQUESTED** [review]
Looks great, but just wondering if we should make the posts and communities pages a bit more consistent because right now the search bar that you have and the search bar that I did for the posts page are different. Also, I do not have the "based on search query..." text under the search bar. Should I also add it in the posts page?
Posts page search bar:
image

**Comment by christopher-alba** [comment]
> Looks great, but just wondering if we should make the posts and communities pages a bit more consistent because right now the search bar that you have and the search bar that I did for the posts page are different. Also, I do not have the "based on search query..." text under the search bar. Should I also add it in the posts page? Posts page search bar: image

Dont worry about the based on search query text its in one of my PRs :)

**Comment by yuchendong13** [comment]
> Looks great, but just wondering if we should make the posts and communities pages a bit more consistent because right now the search bar that you have and the search bar that I did for the posts page are different. Also, I do not have the "based on search query..." text under the search bar. Should I also add it in the posts page? Posts page search bar: image

Thanks for the feedback Trinh, I'll change the styling for the search bar to match your one in the posts page! I currently have it matching with the Navbar, but I do think it'll make more sense to match yours.

**Review by christopher-alba — CHANGES_REQUESTED** [review]
Please fix these issues so we can see the preview on Netlify, Thanks!
image

**Comment by yuchendong13** [comment]
Hi reviewers, could you please double-check the app.js - another PR overwrote my route to the communities page so I have created a separate route for 'CommunitiesPage' (not quite sure what the purpose of this is) and routed the old '/Communities' back to my communities page.

**Review by christopher-alba — APPROVED** [review]
LGTM!

**Review by Tvo465 — APPROVED** [review]
Looks good :)

**Review by qzho236 — APPROVED** [review]

**Pull request merged**
