### PR TITLE
Posts page basic layout

### LINKED ISSUE #32: Posts Page Basic Layout
- contains a list of all the posts (use the existing post preview component)
- contains a searchbar to search all the posts
- contains new post button
image

### PR DESCRIPTION
**Pull request by Tvo465**
# Description

contains a list of all the posts (use the existing post preview component)
contains a searchbar to search all the posts
contains new post button
search function able to filter posts by title
Search function should also include the ability to filter out posts based on the test of the post, this will be made into a new issue.

This is the link to the page for netlify preview: https://deploy-preview-46--uniforum.netlify.app/Posts
## Related Issue

Solves #32 

## Type of change

- [x] New feature (enhancement)

## How Has This Been Tested?

 Manually tested locally.
Chrome using windows 11.

- [x] Manual testing

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [x] Is the code documented, particularly in hard-to-understand areas?
- [x] Does the code build without new warnings?
- [x] Has testing been performed that proves changes are effective and work?
- [x] Has a self- and/or peer-review of the code been performed?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

For more information, refer to the Contributing Guidelines and Code of Conduct links at the bottom of this page.

### CODE REVIEW

**Review by christopher-alba — CHANGES_REQUESTED** [review]
Heya please fix these issues so we can see the Netlify preview, thanks!
image

**Comment by Tvo465** [comment]
> Heya please fix these issues so we can see the Netlify preview, thanks! image

Just fixed it, should be working now.

**Review by hpar461 — APPROVED** [review]
Great Job! The only thing I could barely review about is indentation being four spaces but even that's trivial anyway.  LGTM!

**Review by christopher-alba — APPROVED** [review]
LGTM!

**Pull request merged**
