### PR TITLE
make general fixes

### LINKED ISSUE #53: Make General Fixes in App
- add appropriate links to pages in post preview component
- update readme to include netlify deploy link and Qunzhi Zhou in contributions
- other general fixes that are deemed necessary

### PR DESCRIPTION
**Pull request by christopher-alba**
# Description

- add appropriate links to pages in post preview component
- update readme to include netlify deploy link and Qunzhi Zhou in contributions
- other general fixes that are deemed necessary
- include useEffect hooks to set scroll position to (0,0) on page load on multiple pages
## Related Issue

resolves #53 

## Type of change

- [x] New feature (enhancement)
- [x] Bug fix
- [x] Refactor
- [ ] Breaking change
- [x] Documentation

## How Has This Been Tested?

- [ ] Automated testing
- [x] Manual testing

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [x] Does the code build without new warnings?
- [x] Has testing been performed that proves changes are effective and work?
- [ ] Has a self- and/or peer-review of the code been performed?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

For more information, refer to the Contributing Guidelines and Code of Conduct links at the bottom of this page.

### CODE REVIEW

**Comment by hpar461** [comment]
Hi, love the changes!

Perhaps one potential UI fix would be on the post preview components, where I've noticed that a link icon? has been appearing on the right side of the title. Perhaps this should be removed following the ui prototype design? Final decision is up to you. 
image

**Comment by christopher-alba** [comment]
> Hi, love the changes!
> 
> Perhaps one potential UI fix would be on the post preview components, where I've noticed that a link icon? has been appearing on the right side of the title. Perhaps this should be removed following the ui prototype design? Final decision is up to you. image

Yup that's because the title is now also a link to the particular post (based on its ID) so i felt like it needed a call to action for people to realise they can click on it

**Comment by Xiaoqi510** [comment]
Looks all good now, but just one potential ui issue at the bottom of the communities page, i think we can add **. padding-bottom:20px** for the class **_com-bodyContainer_** in the communities.css. 
Screen Shot 2022-03-20 at 6 24 32 PM

**Comment by hpar461** [comment]
> > Hi, love the changes!
> > Perhaps one potential UI fix would be on the post preview components, where I've noticed that a link icon? has been appearing on the right side of the title. Perhaps this should be removed following the ui prototype design? Final decision is up to you. image
> 
> Yup that's because the title is now also a link to the particular post (based on its ID) so i felt like it needed a call to action for people to realise they can click on it

Right! That's algood then. Thanks!

**Review by yuchendong13 — COMMENTED** [review]
Looking good, thanks for all the hard work! Just following on from Xiaoqi's comment, since we added padding to the communities page, did we also want to pad the bottom of the home and posts page?

**Review by Xiaoqi510 — APPROVED** [review]
Looks quite nice now!

**Review by hpar461 — APPROVED** [review]
LGTM! Great work!

**Comment by christopher-alba** [comment]
> Looking good, thanks for all the hard work! Just following on from Xiaoqi's comment, since we added padding to the communities page, did we also want to pad the bottom of the home and posts page?

Lets make this an issue for the next team :P

**Pull request merged**
