### PR TITLE
New post page layout

### LINKED ISSUE #27: New Post Page
As discussed in [Wireframing / Feature Planning](https://github.com/SE701-T5/Frontend/issues/6):
- contains text box for title
- contains dropdown to select forum the post is for
- contains text area for post description
- contains upload media button for pictures

### PR DESCRIPTION
**Pull request by yuchendong13**
# Description

NOTE: After consulting with Frontend lead @christopher-alba, the justification of the 'Title' and 'Forum selection' fields have been slightly modified from the initial Figma design. The fields now span the whole container instead of being a bit shorter.

- contains text box for title
- contains dropdown to select forum the post is for
- contains text area for post description
- contains upload media button for pictures

## Related Issue

Solves [Issue #27](https://github.com/SE701-T5/Frontend/issues/27)

## Type of change

- [x] New feature (enhancement)

## How Has This Been Tested?

- [x] Manual testing

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [ ] Is the code documented, particularly in hard-to-understand areas?
- [x] Does the code build without new warnings?
- [ ] Has testing been performed that proves changes are effective and work?
- [ ] Has a self- and/or peer-review of the code been performed?
- [x] Have dependent changes been merged and published in downstream modules?
- [ ] Does all new and existing automated testing pass?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

### CODE REVIEW

**Review by christopher-alba — CHANGES_REQUESTED** [review]
Heya its looking good. Could use a title at the top though, maybe something like "New Post Creation" or something.

**Comment by yuchendong13** [comment]
Thanks for the feedback Chris. Yup that's definitely a good point, sorry it slipped my mind since it wasn't on the design but it should be a given.

**Comment by hpar461** [comment]
Hi! A couple of UI issues coming through:

1. as you can see in the image below, when you select the forum dropdown, the title gets pushed to the border but then it overlaps with the border. Prob need some fix.
Screenshot 2022-03-16 오후 9 07 37
 
2. This is just as it is in the figma UI prototype, but considering the overall design of the website, it might be better in terms of overall aesthetics if the corners for the new post component could be rounded a bit; perhaps around 8~10px?

Thanks!

**Comment by yuchendong13** [comment]
Thanks for the review Hyung. I will have a look into the title in border problem as the gap in the border seems to be part of the default material UI design. As for your second point, I definitely agree that rounded corners will look better.

**Review by hpar461 — DISMISSED** [review]
LGTM!

**Review by hpar461 — APPROVED** [review]
LGTM again!

**Review by christopher-alba — APPROVED** [review]
nice!

**Pull request merged**
