### PR TITLE
Create nav bar

### LINKED ISSUE #17: NavBar Component
- Has a dropdown for all the different communities of a user which shows only if a user is logged in
- Can search for specific posts or communities based on a search filter users can select from a dropdown
  - If user clicks a search icon, it begins search with the current keyword in the search box.
- Button to create a new post
  - If user is not logged in it will redirect them to the Login page
  - If user is logged in it will redirect them to New Post page
- Button to create a new community
  - If user is not logged in it will redirect them to the Login page
  - If user is logged in it will redirect them to New Community page
- If user is logged in button for dropdown menu with these options:
  - Profile
  - Logout
- if user is not logged in display a login button and register button that redirects to specified pages

### PR DESCRIPTION
**Pull request by hpar461**
# Description
This implements a nav bar at the top of every page to allow easier navigation between pages and provide utility functionalities such as search bar.

Redirecting features has not been implemented yet due to a relevant react router code not implemented yet.

## Related Issue

Solves #17 

## Type of change

- [x] New feature (enhancement)

## How Has This Been Tested?

- [x] Automated testing
- [x] Manual testing

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [ ] Is the code documented, particularly in hard-to-understand areas?
- [x] Does the code build without new warnings?
- [x] Has testing been performed that proves changes are effective and work?
- [ ] Has a self- and/or peer-review of the code been performed?
- [x] Have dependent changes been merged and published in downstream modules?
- [x] Does all new and existing automated testing pass?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

For more information, refer to the [Contributing Guidelines](../blob/contribution-guidelines/.github/CONTRIBUTING.md) document.

### CODE REVIEW

**Review by christopher-alba — CHANGES_REQUESTED** [review]
Its looking great! Please move the the styles into their own file so the concerns are separate :) Thanks!

**Comment by hpar461** [comment]
> Its looking great! Please move the the styles into their own file so the concerns are separate :) Thanks!

The component style was refactored into a separate file (`NavBar-styles.js`) and those files were relocated to its own folder called `NavBar/`.

**Review by christopher-alba — DISMISSED** [review]
LGTM!

**Review by Xiaoqi510 — DISMISSED** [review]

**Review by yuchendong13 — APPROVED** [review]
Looks amazing!

**Pull request merged**
